services:
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - stripe_pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT_FORWARD}:${DB_PORT}
    restart: always

  server:
    container_name: server
    hostname: api
    build:
      context: ./server
      dockerfile: ../.docker/server.dockerfile
      target: ${APP_ENV}
      args:
        APP_HOME: ${APP_HOME}
    ports:
      - ${API_PORT_FORWARD}:${API_PORT}
      - ${API_DEBUG_PORT_FORWARD}:${API_DEBUG_PORT}
    volumes:
      - .:${APP_HOME}
    links:
      - db

volumes:
  stripe_pgdata:
    external: true
